services:
  web:
    image: ur-web:latest
    container_name: ur-web
    healthcheck:
      test: [ "CMD-SHELL", "node -e \"require('http').get('http://localhost:3000', (res) => process.exit(res.statusCode === 200 ? 0 : 1))\"" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}?schema=public

      ADMIN_ALLOWED_CIDR: ${ADMIN_ALLOWED_CIDR}

      WEBSITE_OWNER: ${WEBSITE_OWNER}
      OWNER_STREET: ${OWNER_STREET}
      OWNER_CITY: ${OWNER_CITY}
      OWNER_COUNTRY: ${OWNER_COUNTRY}
      OWNER_REPRESENTED_BY: ${OWNER_REPRESENTED_BY}
      OWNER_MAIL: ${OWNER_MAIL}

      SECRET: ${SECRET}

      CONTACT_SMTP_HOST: ${CONTACT_SMTP_HOST}
      CONTACT_SMTP_PORT: ${CONTACT_SMTP_PORT}
      CONTACT_SMTP_SECURE: ${CONTACT_SMTP_SECURE}
      CONTACT_SMTP_USER: ${CONTACT_SMTP_USER}
      CONTACT_SMTP_PASSWORD: ${CONTACT_SMTP_PASSWORD}
      CONTACT_MAIL_TO: ${CONTACT_MAIL_TO}

      VERIFICATION_SMTP_HOST: ${VERIFICATION_SMTP_HOST}
      VERIFICATION_SMTP_PORT: ${VERIFICATION_SMTP_PORT}
      VERIFICATION_SMTP_SECURE: ${VERIFICATION_SMTP_SECURE}
      VERIFICATION_SMTP_USER: ${VERIFICATION_SMTP_USER}
      VERIFICATION_SMTP_PASSWORD: ${VERIFICATION_SMTP_PASSWORD}
    ports:
      - "3008:3000"
    restart: unless-stopped
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
